name = "logicalmechanism/assist"
version = "0.4.6"
license = "Apache-2.0"
description = "Aiken Assist Library"

[repository]
user = "logicalmechanism"
project = "assist"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"